CREATE PROCEDURE [dbo].[insertEditedTeacher]
 @FirstName NVARCHAR(50), 
    @MiddleName NVARCHAR(50), 
    @LastName NVARCHAR(50), 
    @RegistrationNumber NVARCHAR(20), 
    @HudumaNumber NVARCHAR(20), 
    @EmployerName NVARCHAR(50), 
    @StaffNumber NVARCHAR(20), 
    @EducationLevel NVARCHAR(50), 
    @IdNumber NVARCHAR(20), 
    @BankName NVARCHAR(50), 
    @PINNUmber NVARCHAR(20), 
    @AccountNumber NVARCHAR(50), 
    @EmailAddress NVARCHAR(50), 
    @PhysicalAddress NVARCHAR(50), 
    @Town NVARCHAR(50), 
    @PhoneNumber1 NVARCHAR(20), 
    @PhoneNumber2 NVARCHAR(20),
    @Id INT,
    @Remarks NVARCHAR(255)
AS
	INSERT INTO EditedTeachers(
                        AccountNumber,
                        BankName,
                        EducationLevel,
                        EmailAddress,
                        EmployerName,
                        FirstName,
                        HudumaNumber,
                        IdNumber,
                        LastName,
                        MiddleName,
                        PhoneNumber1,
                        PhoneNumber2,
                        PhysicalAddress,
                        PINNUmber,
                        RegistrationNumber,
                        StaffNumber,
                        Town, 
                        Id,
                        Remarks
                      )
                      VALUES(
                              @AccountNumber,
                              @BankName,
                              @EducationLevel,
                              @EmailAddress,
                              @EmployerName,
                              @FirstName,
                              @HudumaNumber,
                              @IdNumber,
                              @LastName,
                              @MiddleName,
                              @PhoneNumber1,
                              @PhoneNumber2,
                              @PhysicalAddress,
                              @PINNUmber,
                              @RegistrationNumber,
                              @StaffNumber,
                              @Town,
                              @Id,
                              @Remarks
                            )
